# extend pyproject.toml for requires-python (workaround astral-sh/ruff#10299)
extend = "pyproject.toml"

[lint]
extend-select = [
	"C901", # complex-structure
	"I", # isort
	"PERF401", # manual-list-comprehension
	"W", # pycodestyle Warning
]
ignore = [
	# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
	"W191",
	"E111",
	"E114",
	"E117",
	"D206",
	"D300",
	"Q000",
	"Q001",
	"Q002",
	"Q003",
	"COM812",
	"COM819",
	"ISC001",
	"ISC002",
]

[lint.isort]
combine-as-imports = true
split-on-trailing-comma = false

[format]
# Enable preview to get hugged parenthesis unwrapping and other nice surprises
# See https://github.com/jaraco/skeleton/pull/133#issuecomment-2239538373
preview = true
# https://docs.astral.sh/ruff/settings/#format_quote-style
quote-style = "preserve"
